import { useState } from 'react';
import CaseStudyNav from '@/components/CaseStudyNav';
import Footer from '@/components/Footer';

const ROLES = [
  { id: 'r1', number: '01', name: '预审岗', system: '承担总结描述与主体判断', colour: '#28aede', soft: '#e5f6fc', scope: '主体定义、坏例判断、总结描述', question: '这条任务能否进入后续标注？', copy: '先确认主体与整体事件，为后续两岗建立统一的语义框架。' },
  { id: 'r2', number: '02', name: '画面描述岗', system: '负责静态视觉信息', colour: '#2d8152', soft: '#e4f2e9', scope: '主体、物体、环境、画面文字', question: '画面里有什么，处在什么环境中？', copy: '集中观察稳定的视觉信息，不必同时判断动作、时序与运镜。' },
  { id: 'r3', number: '03', name: '镜头叙事岗', system: '负责动态与镜头信息', colour: '#e4c23e', soft: '#fff8d8', scope: '动作、运镜、方向、速度、时序', question: '谁在变化，镜头如何表达？', copy: '把最容易漏写、错写的运动信息交给专门岗位。' },
  { id: 'r4', number: '04', name: '终审岗', system: '负责风格描述与最终校对', colour: '#ed2323', soft: '#fee8e8', scope: '风格字段、全文一致性、合并导出', question: '四个字段能否合成一条完整 Caption？', copy: '检查风格、重复、事实冲突与遗漏后完成最终交付。' },
];

const PAINS = [
  ['规则过长，学习与记忆负担高', '一名标注员需要在同一条任务中掌握大量规则、例外与字段格式。'],
  ['字段之间高度耦合', '主体、事件、动作、镜头与风格彼此影响，直接按字段拆分容易破坏整条 Caption 的一致性。'],
  ['质量与产能波动', '长字段面对空白输入框，容易出现遗漏、重复与流水账，返修也随之增加。'],
];

export default function CaptionFourRolesCaseStudy() {
  const [activeId, setActiveId] = useState('r1');
  const [demoOpen, setDemoOpen] = useState(false);
  const active = ROLES.find((role) => role.id === activeId) ?? ROLES[0];

  return <div className="min-h-[100dvh] bg-[#f3f6f3] text-[#101716]">
    <CaseStudyNav fixedLanguage="cn" />
    <main className="pt-14">
      <section className="mx-auto grid max-w-[1440px] gap-10 px-6 py-16 md:px-12 md:py-20 xl:grid-cols-[.92fr_1.08fr] xl:px-16">
        <div className="max-w-3xl self-end">
          <p className="font-mono-custom text-[10px] tracking-[.16em] text-[#66746d]">AI PRODUCT / CAPTION PRODUCTION</p>
          <h1 className="mt-5 font-heading text-5xl font-700 leading-[.95] tracking-tight md:text-7xl">Caption<br />四岗位协作标注平台</h1>
          <p className="mt-7 max-w-[58ch] text-base leading-8 text-[#4b5a53] md:text-lg">针对规则过长、字段高度耦合的 Caption 任务，设计可分工、可交接、可质检的数据生产流程。</p>
          <div className="mt-10 flex flex-wrap gap-x-12 gap-y-5 border-t border-[#c4cec7] pt-5"><Meta label="我负责的部分" value="协作流程设计、原型验证与平台需求定义" /><Meta label="小批试点结果" value="准确率约 40% → 80%，单位人效约 +50%" /></div>
        </div>
        <CaptionStructure />
      </section>

      <section className="border-y border-[#c9d3cc] bg-white py-16 md:py-24"><div className="mx-auto max-w-[1440px] px-6 md:px-12 xl:px-16">
        <div className="max-w-4xl"><h2 className="font-heading text-3xl font-700 leading-[1.06] tracking-tight md:text-5xl">规则过长与字段耦合，让长 Caption 难以直接拆分</h2><p className="mt-5 max-w-[70ch] text-base leading-8 text-[#516059] md:text-lg">视频生成模型需要从 Caption 中学习画面内容、元素运动、镜头表达与视觉风格。它们共享同一组主体、事件与时序关系，任何一个字段的判断都会影响其余部分。</p></div>
        <div className="mt-10 grid gap-6 xl:grid-cols-[1.12fr_.88fr]"><FullCaption /><div className="border border-[#bdc9c1] bg-[#f4f7f4] p-6 md:p-8"><p className="font-mono-custom text-[9px] tracking-[.15em] text-[#6d7c74]">痛点 / 仅靠补充 SOP 无法解决</p><div className="mt-7 space-y-7">{PAINS.map(([title, copy], index) => <div key={title} className="grid grid-cols-[34px_1fr] gap-4"><span className="font-mono-custom text-sm text-[#7a887f]">0{index + 1}</span><div><h3 className="font-heading text-xl font-700">{title}</h3><p className="mt-2 text-sm leading-6 text-[#526059]">{copy}</p></div></div>)}</div><p className="mt-8 border-l-2 border-[#101716] pl-4 text-sm leading-6 text-[#33433b]">新增规则、案例与培训会继续增加记忆负荷。直接切分字段又会切断它们之间的依赖关系，因此需要先建立共享语义，再分配专业判断。</p></div></div>
      </div></section>

      <section className="mx-auto max-w-[1440px] px-6 py-16 md:px-12 md:py-24 xl:px-16"><div className="max-w-4xl"><p className="font-mono-custom text-[9px] tracking-[.16em] text-[#68766f]">A / 重新组织协作结构</p><h2 className="mt-4 font-heading text-3xl font-700 leading-[1.06] tracking-tight md:text-5xl">围绕同一语义锚点，拆分四类专业判断</h2><p className="mt-5 max-w-[70ch] text-base leading-8 text-[#516059]">预审先确认主体与整体事件，建立所有字段共用的语义锚点。静态与动态岗位围绕这一锚点分别补充画面与运动信息，终审再统一检查风格、事实与全文一致性。平台将这些依赖关系落实到字段权限、任务状态与合并逻辑中。</p></div>
        <div className="mt-12 grid gap-px overflow-hidden border border-[#b8c5bd] bg-[#b8c5bd] md:grid-cols-2">{ROLES.map((role) => <button key={role.id} type="button" onClick={() => setActiveId(role.id)} className={`min-h-64 p-6 text-left transition-colors md:p-8 ${activeId === role.id ? 'bg-[#101716] text-white' : 'bg-white text-[#101716] hover:bg-[#f6f8f5]'}`}><span className="block h-2 w-12" style={{ background: role.colour }} /><p className={`mt-7 font-mono-custom text-[9px] tracking-[.15em] ${activeId === role.id ? 'text-white/55' : 'text-[#75827b]'}`}>{role.number} / {role.system}</p><h3 className="mt-3 font-heading text-2xl font-700">{role.name}</h3><p className={`mt-3 text-sm leading-6 ${activeId === role.id ? 'text-white/72' : 'text-[#56645d]'}`}>{role.scope}</p></button>)}</div>
        <div className="border border-t-0 border-[#b8c5bd] bg-[#f9fbf8] p-6 md:grid md:grid-cols-[.7fr_1.3fr] md:gap-8 md:p-8"><div><span className="inline-block h-2 w-12" style={{ background: active.colour }} /><p className="mt-4 font-heading text-2xl font-700">{active.name}</p><p className="mt-2 text-sm text-[#65736b]">{active.system}</p></div><div><p className="font-heading text-xl font-700 leading-7">“{active.question}”</p><p className="mt-3 max-w-[58ch] text-base leading-7 text-[#4e5d55]">{active.copy}</p></div></div>
      </section>

      <section className="border-y border-[#c8d2cb] bg-[#e5ece7] py-16 md:py-24"><div className="mx-auto max-w-[1440px] px-6 md:px-12 xl:px-16"><div className="max-w-4xl"><h2 className="font-heading text-3xl font-700 leading-[1.06] tracking-tight md:text-5xl">共享语义锚点，让四岗保持同一条 Caption 的一致性</h2><p className="mt-5 max-w-[70ch] text-base leading-8 text-[#516059]">岗位之间保留明确的依赖关系：总结先建立语义框架，静态与动态围绕同一主体和事件补充，终审检查完整性、重复与事实冲突。每个疑问都可回传到对应岗位处理。</p></div><Workflow /></div></section>

      <section className="mx-auto max-w-[1440px] px-6 py-16 md:px-12 md:py-24 xl:px-16"><div className="grid gap-10 xl:grid-cols-[.72fr_1.28fr]"><div><p className="font-mono-custom text-[9px] tracking-[.16em] text-[#68766f]">R / 试点与结果</p><h2 className="mt-4 font-heading text-3xl font-700 leading-[1.06] tracking-tight md:text-5xl">先在小范围试点，再推进平台适配</h2><p className="mt-5 text-base leading-8 text-[#516059]">四岗位协作试点后，Caption 标注准确率约从 40% 提升至 80%，标注效率提升约 50%。方案已向平台方推进正式适配。</p></div><div className="grid gap-5 sm:grid-cols-2"><Outcome value="40% → 80%" title="Caption 标注准确率" copy="通过四岗位协作流程完成小范围试点验证。" /><Outcome value="+50%" title="标注效率" copy="减少单人处理长 Caption 时的规则切换与记忆负担。" /><Outcome value="4 个岗位" title="可复制的生产单元" copy="各岗位可独立培训、配置 SOP、观察产能和定位质量问题。" /><Outcome value="已提交" title="平台改造需求" copy="多岗作业、字段流转、问题反馈、案例沉淀和规则迭代进入正式方案。" /></div></div></section>

      <section className="border-y border-[#c8d2cb] bg-[#101716] py-16 text-white md:py-20"><div className="mx-auto grid max-w-[1440px] gap-10 px-6 md:px-12 xl:grid-cols-[.72fr_1.28fr] xl:px-16"><div><p className="font-mono-custom text-[9px] tracking-[.16em] text-[#d6c07f]">SCALE REVIEW / 规模化复盘</p><h2 className="mt-4 font-heading text-3xl font-700 leading-[1.06] tracking-tight md:text-5xl">试点证明拆分有效，上线仍要解决交接成本</h2><p className="mt-5 max-w-[58ch] text-base leading-8 text-white/64">40% → 80% 与约 50% 人效提升来自小批流程试点。进入规模化生产后，为控制岗间误差增加的串行质检带来了新的流转成本，因此试点结果不直接等同于线上长期结果。</p></div><div className="grid gap-px bg-white/16 sm:grid-cols-2"><ReviewPoint title="已经验证" copy="围绕共享语义锚点进行岗位拆分，能够降低单人规则切换负担，并改善完整性与一致性。" /><ReviewPoint title="新暴露的问题" copy="岗位越多，交接、等待与全量串行质检越容易抵消并行生产收益。" /><ReviewPoint title="下一版机制" copy="增加自动预检、异常回退与抽检，只有高风险任务进入更重的人工质检链路。" /><ReviewPoint title="需要继续观察" copy="规模化后的单位人效、返修率、跨岗冲突率，以及正式生产结果能否复现实验收益。" /></div></div></section>

      <section className="border-t border-[#c8d2cb] bg-[#111b16] py-16 text-white md:py-20"><div className="mx-auto max-w-[1440px] px-6 md:px-12 xl:px-16"><div className="flex flex-col gap-6 md:flex-row md:items-end md:justify-between"><div className="max-w-3xl"><p className="font-mono-custom text-[9px] tracking-[.16em] text-[#d6c07f]">ORIGINAL RUNNABLE PROTOTYPE</p><h2 className="mt-4 font-heading text-3xl font-700 leading-[1.06] tracking-tight md:text-5xl">直接在页面里阅览原型与后台测速。</h2><p className="mt-5 text-base leading-7 text-white/67">Demo 会自动登录并保留原有的数据包、工作台、总览、流水线与测速功能。任何出现 Caption 正文的位置都会以遮蔽条替代，避免公开样本内容。</p></div><button type="button" onClick={() => setDemoOpen((open) => !open)} aria-expanded={demoOpen} className="shrink-0 border border-[#d6c07f] px-5 py-3 text-sm font-700 text-[#d6c07f] transition-colors hover:bg-[#d6c07f] hover:text-[#132019] active:translate-y-px">{demoOpen ? '收起 Demo' : '展开 Demo 与测速'}</button></div>{demoOpen && <div className="mt-10 overflow-hidden border border-white/20 bg-white"><iframe title="Caption 平台公开阅览" src="http://localhost:3001/?preview=1&view=dash" className="h-[760px] w-full bg-white md:h-[820px]" /></div>}</div></section>
      <section className="border-t border-[#c8d2cb] bg-[#e5ece7] py-12 md:py-16"><div className="mx-auto flex max-w-[1440px] flex-col gap-6 px-6 md:flex-row md:items-end md:justify-between md:px-12 xl:px-16"><div><p className="font-mono-custom text-[9px] tracking-[.15em] text-[#68766f]">DATA PRODUCTION PROTOTYPES</p><h2 className="mt-3 font-heading text-2xl font-700 tracking-tight md:text-3xl">同组案例</h2></div><div className="flex flex-wrap gap-3"><a href="/projects/ruleloop" className="border border-[#101716] px-4 py-3 text-sm font-700 text-[#101716] transition-colors hover:bg-[#101716] hover:text-white">查看 RuleLoop →</a><a href="/projects/data-production-products" className="border border-[#8f9d94] px-4 py-3 text-sm font-700 text-[#34413b] transition-colors hover:bg-white">查看产品原型总览</a></div></div></section>
    </main><Footer fixedLanguage="cn" /></div>;
}

function CaptionStructure() { return <figure className="border border-[#aebbb3] bg-white p-5 md:p-7"><figcaption className="flex justify-between border-b border-[#d7dfd9] pb-4 font-mono-custom text-[9px] tracking-[.14em] text-[#66746d]"><span>流程结构</span><span>一条 Caption 的协作路径</span></figcaption><div className="mt-6 grid items-stretch gap-2 sm:grid-cols-[1fr_auto_1.4fr_auto_1fr]"><ProcessBlock label="原来" title="单人完整处理" copy="同时记忆全部规则" /><span className="hidden items-center text-[#718078] sm:flex">→</span><div className="border border-[#cbd5ce] bg-[#f4f7f4] p-4"><p className="text-xs font-700 text-[#101716]">共享语义锚点</p><p className="mt-2 text-xs leading-5 text-[#5b6961]">先确认主体、事件与时序，再由四岗补充专业判断。</p><div className="mt-4 grid grid-cols-4 gap-1"><span className="h-8 bg-[#28aede]" /><span className="h-8 bg-[#2d8152]" /><span className="h-8 bg-[#e4c23e]" /><span className="h-8 bg-[#ed2323]" /></div></div><span className="hidden items-center text-[#718078] sm:flex">→</span><ProcessBlock label="输出" title="一条最终 Caption" copy="合并、质检、可追溯" /></div><p className="mt-6 text-sm leading-6 text-[#5b6961]">公开页面仅保留字段结构与流程关系，不展示字段内容、内部规则和样本细节。</p></figure>; }
function ProcessBlock({ label, title, copy }: { label: string; title: string; copy: string }) { return <div className="border border-[#cbd5ce] p-4"><p className="font-mono-custom text-[8px] tracking-[.14em] text-[#738079]">{label}</p><p className="mt-4 font-heading text-lg font-700">{title}</p><p className="mt-2 text-xs leading-5 text-[#5b6961]">{copy}</p></div>; }
function FullCaption() { return <article className="border border-[#b8c5bd] bg-[#101a15] p-6 text-white md:p-8"><p className="font-mono-custom text-[9px] tracking-[.15em] text-[#d6c07f]">原来由一个人完成的一整条 Caption</p><p className="mt-3 text-sm leading-6 text-white/64">以下只保留字段结构。实际作业中，每一段都有大量观察信息、格式要求与禁用表达，需要标注员在同一条任务中持续切换判断。</p><div className="mt-7 space-y-3"><MaskedField name="总结描述" colour="#28aede" /><MaskedField name="静态描述" colour="#2d8152" /><MaskedField name="动态描述" colour="#e4c23e" /><MaskedField name="风格描述" colour="#ed2323" /></div></article>; }
function MaskedField({ name, colour }: { name: string; colour: string }) { return <div className="border border-white/15 p-4"><span className="text-xs font-700" style={{ color: colour }}>{name}</span><div className="mt-3 flex gap-2"><span className="h-2 w-5/12 bg-white/16" /><span className="h-2 w-3/12 bg-white/16" /><span className="h-2 flex-1 bg-white/16" /></div></div>; }
function Workflow() { return <div className="mt-12 overflow-hidden border border-[#aebbb3] bg-[#f8faf7]"><div className="grid gap-px bg-[#b8c5bd] md:grid-cols-[1fr_auto_1fr_auto_1fr]"><Flow label="1. 总结" title="先建立整体语义" copy="定义主体、场景与事件" colour="#28aede" /><Arrow /><div className="grid gap-px bg-[#b8c5bd] sm:grid-cols-2"><Flow label="2. 静态" title="补画面信息" copy="主体、场景、文字" colour="#2d8152" /><Flow label="3. 动态" title="补运动与镜头" copy="动作、时序、运镜" colour="#e4c23e" /></div><Arrow /><Flow label="4. 风格 / 终审" title="合并并检查一致性" copy="避免重复、冲突与遗漏" colour="#ed2323" /></div><div className="grid gap-6 p-6 md:grid-cols-3"><p className="text-sm leading-6 text-[#4f5d56]">每个岗位只编辑自己的字段，降低记忆成本。</p><p className="text-sm leading-6 text-[#4f5d56]">静态和动态在同一语义框架下协作，避免各自描述不同的主体或事件。</p><p className="text-sm leading-6 text-[#4f5d56]">合并与质检检查字段是否互补、重复、冲突或漏掉核心动作。</p></div></div>; }
function Flow({ label, title, copy, colour }: { label: string; title: string; copy: string; colour: string }) { return <div className="min-h-48 bg-white p-6"><span className="block h-2 w-10" style={{ background: colour }} /><p className="mt-5 font-mono-custom text-[9px] tracking-[.14em] text-[#75827b]">{label}</p><h3 className="mt-2 font-heading text-xl font-700">{title}</h3><p className="mt-3 text-sm leading-6 text-[#57655e]">{copy}</p></div>; }
function Arrow() { return <div className="hidden items-center justify-center bg-[#e5ece7] font-mono-custom text-xl text-[#647269] md:flex">→</div>; }
function Meta({ label, value }: { label: string; value: string }) { return <div><p className="font-mono-custom text-[8px] tracking-[.15em] text-[#738079]">{label}</p><p className="mt-2 font-heading text-lg font-700">{value}</p></div>; }
function Outcome({ value, title, copy }: { value: string; title: string; copy: string }) { return <article className="border border-[#b8c5bd] bg-white p-6"><p className="font-heading text-3xl font-700 tracking-tight">{value}</p><h3 className="mt-5 font-heading text-lg font-700">{title}</h3><p className="mt-2 text-sm leading-6 text-[#596760]">{copy}</p></article>; }
function ReviewPoint({ title, copy }: { title: string; copy: string }) { return <article className="bg-[#101716] p-6"><h3 className="font-heading text-xl font-700">{title}</h3><p className="mt-3 text-sm leading-6 text-white/62">{copy}</p></article>; }
